### ISSUE TITLE
Flickering issue with intergrations page search bar

### ISSUE THREAD

**Issue by zadeviggers** [withastro/astro.build#269] opened 2022-09-01 04:51 UTC
When a cursor hovers over the search icon on the integrations page, a bunch of jumping/flickering occurs. See video.

https://user-images.githubusercontent.com/74938858/187833721-933c6f84-b89a-4b3c-8740-e82269e99270.mp4

Occurs in Firefox 104.0.1 on MacOS 12.5.1.

**Comment by delucis** [comment] 2022-09-01 15:32
Yikes! Thanks for the report @zadeviggers

**Comment by swift502** [comment] 2022-09-02 09:47
![](https://user-images.githubusercontent.com/24359130/188112299-3b99cbb9-6597-4f59-a90b-fa8236312ad5.gif)

**Comment by mrienstra** [comment] 2022-09-22 18:12
This happen with Chrome v105 MacOS as well, but I don't think it's a browser-specific bug.

What seems to be happening is that the expanding search input collides with the "Collections" `<ul>` list. It only happens at certain widths, but one of those widths happens to be 1440px, which is not terribly uncommon!

If I resize the window, I can find widths where it does not occur, e.g. at 1260px, the last "Collection" `<li>` ("accessibility") wraps onto a 2nd line, so there's enough room for the search input. Though at this width, the vertical alignment looks off (to my eye), it's somewhere between middle and bottom aligned. I think keeping it aligned with the first row of `<li>`s would be the jam.

I can also delete one of the `<li>`s to make room for the search input (for triaging purposes, obviously not a solution).

A) In this line:
https://github.com/withastro/astro.build/blob/6c3d7b7/src/components/Search.astro#L112
Change: `2.5rem` --> `9.6rem`
... Makes it so the <section> wrapping the search input doesn't get wider on hover or focus.

**For vertical alignment:**

B) In the search section CSS:
https://github.com/withastro/astro.build/blob/6c3d7b7/src/components/Search.astro#L108-L113
... Add `margin-top: 0.9rem;` or `padding-top: 0.9rem;` (or maybe more like 0.85rem?)

C) In this line:
https://github.com/withastro/astro.build/blob/6c3d7b7/src/layouts/Catalog.astro#L47
Change `md:items-end` --> `md:items-start`

Er, these are just some quick drive-by suggestions, for desktop only, didn't check very carefully on mobile, but looks like the only noticable difference is the `margin-top` added in change (B).

B2) Change (b) could be added inside the `@media(hover: hover) {` media query that begins on line 159:

```css
    @media(hover: hover) {
        section {
            margin-top: 0.86rem;
        }
        label {
```

Huh, OK, playing with it a bit more, change (A) is not needed (although it is does fix the flickering by itself), (C) alone fixes the problem. But then something else is needed to get a nice vertical alignment, I personally think (B2) looks nice.

... Wow, so weird, now I can't reproduce the issue. I figured the code or data changed, but I don't see any changes on `main` or anything new in [Actions](https://github.com/withastro/astro.build/actions).

Oh, I guess this went live somehow @tony-sull?
https://github.com/withastro/astro.build/commit/36a30bb

**Comment by tony-sull** [comment] 2022-09-27 13:34
Yep that's definitely a bad experience!  Fixed in the latest release, the search bar needed to claim it's full width whether it's open or closed to make sure nothing shifts when opened :+1:

**Closed by tony-sull** 2022-09-27 13:34 UTC
Labels: bug
