### ISSUE TITLE
SHOWCASE: Jamstacker Studio

### ISSUE THREAD

**Issue by michael-andreuzza** [withastro/astro.build#239] opened 2022-08-14 14:59 UTC
### Website title

Jamstacker Studio

### Short description and preview image

Premium web design & development for startups with fixed timeline & price.

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/34077176/184542817-9fb1141b-8114-486a-8ab8-bcef9bb81b7f.png">

### Public website URL

https://jamstacker.studio/

**Comment by tony-sull** [comment] 2022-08-16 14:06
Closing as a duplicate of #238 👍

**Closed by tony-sull** 2022-08-16 14:06 UTC
