### ISSUE TITLE
Astro.build homepage surprisingly slow to scroll in Firefox once fully loaded

### ISSUE THREAD

**Issue by dandv** [withastro/astro.build#997] opened 2024-03-04 04:16 UTC
I was evaluating site generators and looked at Astro. Tested against https://astro.build in Firefox 121.0 64-bit on Fedora 38. Issue does not occur in Chromium or on other sites in Firefox.

### Describe the Bug

After astro.build is completely loaded, scrolling is surprisingly slow, with portions of the webpage needing up to one second to re-render (see [screencast](https://youtu.be/jQHYtrnQg5U)). Firefox isn't able to keep up with rendering if holding PgUp/PgDn for auto-repeat.

This may well be a Firefox issue. However, it can turn off those who evaluate Astro for their needs using Firefox, so it's in Astro's interest to report the issue upstream and find a workaround in the interim.

### Screencast

https://youtu.be/jQHYtrnQg5U

**Comment by bluwy** [comment] 2024-03-04 07:30
Possible duplicate of https://github.com/withastro/astro.build/issues/736

**Closed** 2024-07-23 13:50 UTC
